from tortoise import Model, fields


class ChessProfile(Model):
    id = fields.BigIntField(pk=True)
    user = fields.ForeignKeyField("models.User", related_name="chess_profile", on_delete=fields.CASCADE, unique=True)
    rating = fields.IntField(default=1000)
    games_count = fields.BigIntField(default=0)
    wins = fields.BigIntField(default=0)
    losses = fields.BigIntField(default=0)
    draws = fields.BigIntField(default=0)
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)


class CheckersProfile(Model):
    id = fields.BigIntField(pk=True)
    user = fields.ForeignKeyField("models.User", related_name="checkers_profile", on_delete=fields.CASCADE, unique=True)
    rating = fields.IntField(default=1000)
    games_count = fields.BigIntField(default=0)
    wins = fields.BigIntField(default=0)
    losses = fields.BigIntField(default=0)
    draws = fields.BigIntField(default=0)
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)


class ChessGame(Model):
    id = fields.BigIntField(pk=True)
    white_player = fields.ForeignKeyField("models.User", related_name="chess_games_as_white")
    black_player = fields.ForeignKeyField("models.User", related_name="chess_games_as_black")
    winner = fields.ForeignKeyField("models.User", related_name="chess_games_won", null=True)
    chat_id = fields.BigIntField()
    chat_type = fields.CharField(max_length=20)
    message_id = fields.BigIntField(null=True)
    inline_message_id = fields.CharField(max_length=255, null=True)
    fen = fields.TextField()
    selected_square = fields.CharField(max_length=2, null=True)
    status = fields.CharField(max_length=30, default="active")
    turn = fields.CharField(max_length=5, default="white")
    result_reason = fields.CharField(max_length=50, null=True)
    reward_amount = fields.IntField(default=0)
    time_control = fields.IntField()
    white_time_left = fields.IntField()
    black_time_left = fields.IntField()
    last_move_at = fields.DatetimeField(null=True)
    increment_seconds = fields.IntField(default=0)
    draw_offered_by = fields.ForeignKeyField("models.User", related_name="chess_draw_offers", null=True)
    created_at = fields.DatetimeField(auto_now_add=True)
    started_at = fields.DatetimeField(null=True)
    finished_at = fields.DatetimeField(null=True)
    updated_at = fields.DatetimeField(auto_now=True)


class CheckersGame(Model):
    id = fields.BigIntField(pk=True)
    white_player = fields.ForeignKeyField("models.User", related_name="checkers_games_as_white")
    black_player = fields.ForeignKeyField("models.User", related_name="checkers_games_as_black")
    winner = fields.ForeignKeyField("models.User", related_name="checkers_games_won", null=True)
    chat_id = fields.BigIntField()
    chat_type = fields.CharField(max_length=20)
    message_id = fields.BigIntField(null=True)
    inline_message_id = fields.CharField(max_length=255, null=True)
    board_state = fields.JSONField()
    selected_square = fields.CharField(max_length=2, null=True)
    forced_square = fields.CharField(max_length=2, null=True)
    status = fields.CharField(max_length=30, default="active")
    turn = fields.CharField(max_length=5, default="white")
    result_reason = fields.CharField(max_length=50, null=True)
    reward_amount = fields.IntField(default=0)
    time_control = fields.IntField()
    white_time_left = fields.IntField()
    black_time_left = fields.IntField()
    last_move_at = fields.DatetimeField(null=True)
    increment_seconds = fields.IntField(default=0)
    draw_offered_by = fields.ForeignKeyField("models.User", related_name="checkers_draw_offers", null=True)
    created_at = fields.DatetimeField(auto_now_add=True)
    started_at = fields.DatetimeField(null=True)
    finished_at = fields.DatetimeField(null=True)
    updated_at = fields.DatetimeField(auto_now=True)


class ChessMove(Model):
    id = fields.BigIntField(pk=True)
    game = fields.ForeignKeyField("models.ChessGame", related_name="moves", on_delete=fields.CASCADE)
    player = fields.ForeignKeyField("models.User", related_name="chess_moves")
    move_number = fields.IntField()
    from_square = fields.CharField(max_length=2)
    to_square = fields.CharField(max_length=2)
    promotion = fields.CharField(max_length=1, null=True)
    san = fields.CharField(max_length=20)
    fen_after = fields.TextField()
    created_at = fields.DatetimeField(auto_now_add=True)


class CheckersMove(Model):
    id = fields.BigIntField(pk=True)
    game = fields.ForeignKeyField("models.CheckersGame", related_name="moves", on_delete=fields.CASCADE)
    player = fields.ForeignKeyField("models.User", related_name="checkers_moves")
    move_number = fields.IntField()
    from_square = fields.CharField(max_length=2)
    to_square = fields.CharField(max_length=2)
    captured_squares = fields.JSONField(default=list)
    became_king = fields.BooleanField(default=False)
    board_after = fields.JSONField()
    created_at = fields.DatetimeField(auto_now_add=True)
